source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBAudienceNetwork'
pod 'AFNetworking', '~> 2.5'
pod 'Appirater'
pod 'SDWebImage', '~>3.7'
pod 'Fabric'
pod 'Crashlytics'
pod 'MobileAppTracker'
